### ISSUE TITLE
智米电暖器无法显示

### ISSUE THREAD

**Issue by jennergray** [fineemb/Smartmi-smart-heater#1]
你好，我按照你的方法，把 miheater 文件夹放进了 custom_components，在配置文件里面也加入了
`climate: 
  - platform: miheater
    host: 192.168.50.15
    token: 77ab858ef97f3404d63d440c51e19288
    name: 取暖器
`

为啥还是没有显示实体呢？ token 这些都是对的。

**Comment by jennergray** [comment]
Thu Feb 13 2020 11:55:39 GMT+0800 (CST)

miheater: Error on device update!
Traceback (most recent call last):
  File "/config/custom_components/miheater/climate.py", line 203, in async_update
    power = self._device.send('get_prop', ['power'])[0]
  File "/usr/local/lib/python3.7/site-packages/miio/device.py", line 291, in send
    raise DeviceError(error)
miio.exceptions.DeviceError: {'code': -5001, 'message': 'command error'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 459, in async_device_update
    await self.async_update()
  File "/usr/local/lib/python3.7/asyncio/coroutines.py", line 120, in coro
    res = func(*args, **kw)
  File "/config/custom_components/miheater/climate.py", line 233, in async_update
    except DeviceException:
NameError: name 'DeviceException' is not defined

这个是 hassio 的日志报告

**Comment by fineemb** [comment]
取暖器的型号是什么

**Comment by jennergray** [comment]
> 取暖器的型号是什么

智米电暖气智能版1S

**Comment by fineemb** [comment]
这个型号不支持,或者协议有区别.
需要自己抓包后确认一下
