### ISSUE TITLE
Convector Heater 1S - error

### ISSUE THREAD

**Issue by devpitx** [fineemb/Smartmi-smart-heater#8]
miheater: Error on device update!
Traceback (most recent call last):
  File "/config/custom_components/miheater/climate.py", line 203, in async_update
    power = self._device.send('get_prop', ['power'])[0]
  File "/usr/local/lib/python3.8/site-packages/miio/device.py", line 124, in send
    return self._protocol.send(command, parameters, retry_count)
  File "/usr/local/lib/python3.8/site-packages/miio/miioprotocol.py", line 196, in send
    raise DeviceError(error)
miio.exceptions.DeviceError: {'code': -5001, 'message': 'command error'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
    await task
  File "/usr/local/lib/python3.8/asyncio/coroutines.py", line 124, in coro
    res = func(*args, **kw)
  File "/config/custom_components/miheater/climate.py", line 233, in async_update
    except DeviceException:
NameError: name 'DeviceException' is not defined

**Comment by devpitx** [comment]
"model":"zhimi.heater.zb1"

**Comment by devpitx** [comment]
https://github.com/fineemb/Smartmi-smart-heater/issues/5 
some issue..
